# Dependencies
markdown:	kramdown
# Permalinks
permalink:	/blog/:title

# Setup
title:            一个希望变的有趣的小网站
tagline:          'blog'
description:      '关心科技和人文，热爱独立游戏、摄影、侦探小说粉，会打乒乓球，偶尔还会一些有趣的DIY手工，渴望学习绘画。_(:з」∠)__'
url:              http://ytysj.github.io
baseurl:          
commentsystem:    Duoshuo
disqus:           example

author:
  name:           ytysj
  url:            

paginate:         5

# Custom vars
icon:             /assets/images/icon.png
cover:            /assets/images/cover.jpg

social:
  - icon:         weibo
    url:          http://weibo.com/3493499301/profile?rightmod=1&wvr=6&mod=personinfo&is_all=1
    desc:         Follow me on weibo

  - icon:         github
    url:          https://github.com/ytysj
    desc:         Fork me on github

  - icon:         wechat
    url:          
    desc:         Contenct my wechat ytysj_YCH

  - icon:         feed
    url:          
    desc:         

menu:
  - title:        Home
    url:          /

  - title:        About
    url:          /about

copyright:
  author:         ytysj
  url:            http://ytysj.github.io
  type_title:     Some rights reserved
  type_url:       http://creativecommons.org/licenses/by-nc/2.5

parallax:         false

gems: [jekyll-paginate]
# Google Analytics (add the UA Code, e.g.: UA-xxxxxxxx-1)
google_analytics:  UA-75857373-1

# Default Theme Color for Chrome on Android Lollipop (Use RGB ColorCode without `#`, e.g.: `db5945`)
theme_color:       7E9576
